# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Miususario',
            new_name='MiUsuario',
        ),
    ]
